### ISSUE TITLE
Div usage

### ISSUE THREAD

**Issue by farishkash** [Pcole1/prj-rev-bwfs-dasmoto#1]
The idea of a div is place a section of html in each. You should move the div to hold the whole section.  As you progress you will see why code is structure like this but a lot of this is management control.

Your code 

```
<div class="Brushes">
  | <h2>Brushes</h2>
  | </div>
  | <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg">
  | <h3>Hacksaw Brushes</h3>
  | <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <a class="StartingAtPrice">Starting at $3.00 / brush.</a></p>
```

My code and all I did was move the </div> to the bottom.  You would then move your .Brushes class to the h2 line.  

```
<div>
  | <h2 class="Brushes">Brushes</h2>

  | <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg">
  | <h3>Hacksaw Brushes</h3>
  | <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <a class="StartingAtPrice">Starting at $3.00 / brush.</a></p>

</div>
```

**Comment by Pcole1** [comment]
Ah ok, makes sense!  I actually debated about moving the div down below the whole Brushes section like you did but since I was only dealing with Brushes looking a certain way in CSS I divided just the Brushes header.  But the thing I didn't think of was to put the class in the header like you did, so therefore I could put the class in the header and the CSS would still only affect the Brushes header, that's why I divided only the header cuz I put the class in the div instead of the header.  Thanks!
